plnoun = input("Enter a Plural Noun: ")
adj = input("Enter an adjective: ")
body_part = input("Enter a part of the body: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
noun3 = input("Enter another noun: ")
noun4 = input("Enter another noun: ")
noun5 = input("Enter another noun: ")
noun6 = input("Enter another noun: ")
noun7 = input("Enter another (7) noun: ")
alphabet_letter = input ("Enter a letter of the alphabet: ")
alphabet_letter2 = input("Enter another letter of the alphabet: ")
noun8 = input("Enter a noun (8): ")
plnoun2 = input("Enter a Plural Noun: ")
noun9 = input("Enter a noun: ")
body_part2 = input("Enter a body part: ")

print("A great word game to play in the car is Mad " + plnoun + ".")
print("Here are the ridiculously " + adj + " instructions. A reader has a Mad Libs book in one" + body_part)
print(" and a pencil or " + noun1 + " in the car for a part of speech (noun, verb, adjective, or " + noun2 + ") to fill in the blanks.")
print("In case you've forgotten, an adjective is a word used to modtify something or some " + noun3 + ". A noun is the name of a person, " + noun4 + ", or " + noun5 + ".")
print("A verb is an action " + noun6 + ". An adverb usually ends in the letters " + alphabet_letter + " and " + alphabet_letter2 + " and modifies a/an " + noun7 + ".")
print("When all the blank " + plnoun2 + " are filled in , th ereader reads the finished " + noun8 + "aloud. The completed story is usualy greeted with shrieks of joy, hoots of " + noun9 + ", and much " + body_part2 + "clapping.")
